version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: memdrill
  backend:
    build: memdrill-backend
    environment:
      MYSQL_HOST: db
      MYSQL_PASSWORD: password
      JWT_SECRET: supersecret
    ports:
      - 3000:3000
    links:
      - db
